<?php
/**
 * Site Configuration — A&S Contracting Services
 * Generated by Phase 1 scaffold from build-plan.json.
 *
 * Single source of truth for site-wide variables. Every page includes this
 * (via head.php/nav.php/footer.php) using $_SERVER['DOCUMENT_ROOT'] — never
 * relative paths. Each page sets its own $canonicalUrl before including head.php.
 */

// ─── Business Identity ─────────────────────────────────────────────────────
$slug            = 'a-s-contracting-services-v7';   // exact build directory name
$clientSlug      = $slug;                            // alias
$siteName        = 'A&S Contracting Services';
$companyName     = $siteName;
$tagline         = 'Building, Repairing, and Improving Homes Across Warrenton and Surrounding Areas.';
$industry        = 'general contractor';

// ─── Contact ───────────────────────────────────────────────────────────────
$phone           = '(636) 359-7204';        // display format
$phoneTel        = '+16363597204';           // tel: / sms: href format
$phoneSecondary  = '';
$email           = 'blake@ascontractingservices.com';
$contactPhone    = $phone;   // alias used by legal-compliance templates
$contactEmail    = $email;   // alias used by legal-compliance templates
$businessHours   = 'Mon–Fri 7am–6pm · Sat 8am–3pm';

// ─── Address ───────────────────────────────────────────────────────────────
$addressStreet   = '';
$addressCity     = 'Warrenton';
$addressState    = 'MO';
$addressZip      = '63383';
$addressPublic   = true;
$businessAddress = trim($addressStreet . ', ' . $addressCity . ', ' . $addressState . ' ' . $addressZip, ', ');

// Structured address array (for schema / templates)
$address = [
    'street' => $addressStreet,
    'city'   => $addressCity,
    'state'  => $addressState,
    'zip'    => $addressZip,
];

// ─── Domain / URLs ─────────────────────────────────────────────────────────
// No production_domain in build-plan.json → default to the preview URL.
$domain          = 'a-s-contracting-services-v7.pageone.cloud';
$siteUrl         = 'https://' . $domain;
// NOTE: $canonicalUrl is NOT set here — each page sets it before head.php.

// ─── SEO Keywords ──────────────────────────────────────────────────────────
$primaryKeyword  = 'general contractor warrenton mo';

$secondaryKeywords = [
    'roofing contractor warrenton mo',
    'siding contractor warrenton mo',
    'gutter installation warrenton mo',
    'windows and doors contractor warrenton mo',
    'roof replacement warrenton mo',
    'exterior home repair warrenton mo',
    'roofing and siding warrenton mo',
    'contractor warren county mo',
    'home remodeling warrenton mo',
    'soffit and fascia installation warrenton mo',
];

// ─── Services ──────────────────────────────────────────────────────────────
$services = [
    [
        'name'        => 'Roofing',
        'slug'        => 'roofing',
        'description' => 'Professional roofing installation, repair, and replacement services for residential and commercial properties. Our experienced team ensures quality craftsmanship and long-lasting protection for your home.',
        'keywords'    => ['roofing contractor warrenton mo', 'roof repair warrenton', 'residential roofing services', 'roof installation', 'roofing company missouri'],
    ],
    [
        'name'        => 'Siding',
        'slug'        => 'siding',
        'description' => "High-quality siding installation and repair to enhance your home's curb appeal and weather protection. We offer a variety of materials and styles to match your home's aesthetic.",
        'keywords'    => ['siding contractor warrenton mo', 'siding installation', 'vinyl siding warrenton', 'exterior siding repair', 'home siding contractor missouri'],
    ],
    [
        'name'        => 'Gutters',
        'slug'        => 'gutters',
        'description' => 'Expert gutter installation, cleaning, and maintenance to protect your home from water damage. Our durable gutter systems keep your foundation and landscaping safe.',
        'keywords'    => ['gutter installation warrenton mo', 'gutter repair warrenton', 'gutter cleaning services', 'seamless gutters missouri', 'residential gutters'],
    ],
    [
        'name'        => 'Soffit',
        'slug'        => 'soffit',
        'description' => "Professional soffit installation and repair to improve ventilation and protect your home's undercarriage. Quality soffit work enhances both functionality and appearance.",
        'keywords'    => ['soffit installation warrenton mo', 'soffit repair', 'soffit contractor', 'fascia and soffit warrenton', 'home soffit services missouri'],
    ],
    [
        'name'        => 'Fascia',
        'slug'        => 'fascia',
        'description' => "Durable fascia installation and replacement to protect your roof edges and improve your home's exterior appearance. We use premium materials for long-term performance.",
        'keywords'    => ['fascia installation warrenton mo', 'fascia repair', 'fascia replacement', 'soffit and fascia contractor', 'roofline repair missouri'],
    ],
    [
        'name'        => 'Windows & Doors',
        'slug'        => 'windows-doors',
        'description' => 'Custom window and door installation services that enhance energy efficiency and curb appeal. We offer quality products with professional installation for your home.',
        'keywords'    => ['window installation warrenton mo', 'door installation warrenton', 'replacement windows missouri', 'patio doors contractor', 'home windows and doors'],
    ],
    [
        'name'        => 'Full Scale Interior Work',
        'slug'        => 'full-scale-interior-work',
        'description' => "Comprehensive interior renovation and construction services including drywall, flooring, painting, and custom finishes. Transform your home's interior with our expert craftsmanship.",
        'keywords'    => ['interior remodel warrenton mo', 'home renovation warrenton', 'interior construction services', 'remodeling contractor missouri', 'full interior renovation'],
    ],
    [
        'name'        => 'Exterior Work',
        'slug'        => 'exterior-work',
        'description' => "Complete exterior construction and renovation services including siding, roofing, and landscaping integration. Protect and enhance your home's outdoor appearance.",
        'keywords'    => ['exterior work warrenton mo', 'exterior contractor', 'home exterior renovation', 'exterior construction missouri', 'property exterior services'],
    ],
    [
        'name'        => 'Dry Wall',
        'slug'        => 'dry-wall',
        'description' => 'Professional drywall installation, finishing, and repair for smooth, flawless interior walls. Our skilled team ensures quality results for residential and commercial projects.',
        'keywords'    => ['drywall contractor warrenton mo', 'drywall installation', 'drywall repair warrenton', 'drywall finishing services', 'interior drywall missouri'],
    ],
    [
        'name'        => 'General Contracting',
        'slug'        => 'general-contracting',
        'description' => 'Full-service general contracting for residential and commercial projects of any size. From planning to completion, we manage every aspect of your construction project.',
        'keywords'    => ['general contractor warrenton mo', 'general contracting services', 'construction contractor missouri', 'residential construction warrenton', 'home builder services'],
    ],
];

// ─── Service Areas ─────────────────────────────────────────────────────────
$serviceAreas = [
    ['city' => 'Warrenton',   'state' => 'MO', 'zip' => '63383', 'primary' => true],
    ['city' => 'Foristell',   'state' => 'MO', 'zip' => '',      'primary' => false],
    ['city' => 'Jonesburg',   'state' => 'MO', 'zip' => '',      'primary' => false],
    ['city' => 'Troy',        'state' => 'MO', 'zip' => '',      'primary' => false],
    ['city' => 'Washington',  'state' => 'MO', 'zip' => '',      'primary' => false],
    ['city' => 'Wentzville',  'state' => 'MO', 'zip' => '',      'primary' => false],
    ['city' => 'Wright City', 'state' => 'MO', 'zip' => '',      'primary' => false],
];
$serviceRadius = 50;   // miles from Warrenton

// ─── Social Links ──────────────────────────────────────────────────────────
$socialLinks = [
    // none provided in intake
];

// ─── Analytics / Verification ──────────────────────────────────────────────
$googleAnalyticsId = 'G-XXXXXXXXXX';   // placeholder — replace with client's GA4 ID at launch
$ga4MeasurementId  = $googleAnalyticsId;
$gscVerification   = '';               // Google Search Console meta content value

// ─── Business Details ──────────────────────────────────────────────────────
$yearsInBusiness  = 3;
$yearEstablished  = 2023;   // (int)date('Y') - $yearsInBusiness
$ownerName        = 'Blake Alger';

$usps = [
    'Licensed & insured in Missouri',
    'Free estimates — no obligation',
    '50-mile service radius from Warrenton',
    'Self-performed work — no subcontractors',
    '5-star Google rated',
    'Same crew start to finish',
];

$aboutDescription = 'A&S Contracting Services is a licensed and insured general contractor serving residential and commercial clients within 50 miles of Warrenton, MO. The company self-performs roofing, siding, gutters, drywall, windows, and full-scale renovations — no trade gaps, no subcontracted surprises. Founded with a focus on roofing and exterior work, A&S expanded to offer a full range of residential construction services under one licensed roof, providing consistent quality from a single accountable team across Warren County and central Missouri.';

$certifications = [
    'Licensed Missouri general contractor',
    'Fully insured',
];

// ─── Design / Brand Colors ─────────────────────────────────────────────────
$colors = [
    'primary'   => '#000000',   // very dark / black
    'secondary' => '#ffffff',   // white
    'accent'    => '#c0c2c4',   // light grey / silver
];
$designArchetype = 'bold-industrial';   // Phase 2, 2026-09-08

// ─── Legal / Compliance ────────────────────────────────────────────────────
$entityType       = '';    // [VERIFY] entity type not provided in intake (LLC / Sole Prop / Corp)
$stateOfFormation = 'MO';  // Terms governing law

// ─── Reviews (real GBP reviews from intake) ──────────────────────────────────
$reviews = [
    ['author' => 'Marcus H.',   'rating' => 5, 'text' => 'Had A&S replace the entire roof on our home after hail damage last spring. They came out fast, gave us a fair written quote, and the crew was professional from start to finish. Roof looks incredible and our insurance claim went smoothly with their documentation.'],
    ['author' => 'Jennifer K.', 'rating' => 5, 'text' => 'We needed new siding and gutters on our place outside Warrenton. A&S was the most professional of the three contractors we got quotes from — they showed up when they said they would, communicated clearly, and finished ahead of schedule. Very happy we went with them.'],
    ['author' => 'Robert T.',   'rating' => 5, 'text' => 'These guys did a full interior renovation — drywall, trim, paint — on a room addition at our house near Wright City. Great craftsmanship, clean job site every day, and they handled everything themselves without subbing it out. Will absolutely hire again.'],
    ['author' => 'Diane L.',    'rating' => 5, 'text' => 'We replaced the soffit and fascia on our older farmhouse and A&S matched everything perfectly to the existing roofline. The estimate was detailed and exactly what we paid. No surprises, no upselling. That kind of straightforward work is hard to find.'],
];

// ─── Google Business Profile ───────────────────────────────────────────────
$googleBusinessProfileUrl = '';
$gbpPlaceId               = '';
$gbpMapEmbed              = '';
$directionsUrl            = '';
$reviewRequestUrl         = '';

// ─── Lead Notification ─────────────────────────────────────────────────────
$leadNotificationEmail = 'blake@ascontractingservices.com';
$leadNotificationPhone = '+16363597204';

// ─── Form Action (Formsubmit.co — 2026-07-11 standard) ───────────────────────
$formAction = 'https://db.pageone.cloud/functions/v1/leads/a-s-contracting-services-v7'; // Page One leads endpoint (no Formsubmit, Sep 2026)

// ─── Tier ──────────────────────────────────────────────────────────────────
$tier = 'premium';   // basic | standard | premium

// ─── CSS Cache-Bust (SINGLE source of truth) ─────────────────────────────────
// Bump on every framework.css change. Pages must NEVER set their own $cssVersion.
$cssVersion = '4';

// ─── Lead Attribution (v6.3) — first-touch cookie + p1_attribution_fields() ───
// Sets the first-party cookie BEFORE any output. Never edit attribution.php.
require_once __DIR__ . '/attribution.php';
$leadsFormSecret = 'bac7714a8f41505ab12d75311ccbb11a6374e38b1a010d69111c84a652cfa0f3'; // spam-shield HMAC (matches leads fn LEADS_FORM_SECRET)
